### ISSUE TITLE
[Feature] Отображать список с результатами поиска

### ISSUE THREAD

**Issue by Konstantin86** [Konstantin86/Git-Hitcher#17]
- Отображать сбоку в панеле поиска
- Если выбран попутчик поиск ищет маршруты водителей и наоборот
- Отображать на карте только текущий выбранный из списка результатов поиска

**Comment by Konstantin86** [comment]
Элемент управления для списка маршрутов - http://getbootstrap.com/components/#list-group-custom-content

**Comment by Konstantin86** [comment]
https://docs.angularjs.org/guide/directive - сделать повторно используемое view на основе директивы и юзать при отображении маршрутов и списка найденных маршрутов

**Comment by Konstantin86** [comment]
- Заголовок поиск переименовать на более общий  - "Маршруты"
- После поиска переходить в состояние routeListState
  - Скрывать фильтр (т.е. поля откуда, куда и кол-во маршрутов)
  - Скрывать все маршруты на карте
  - Отображать найденные маршруты (директива routeListView)
  - Обрабывать выбор (клик - показать маршрут) и mouseenter и mouseleave (подсветка) по маршрутам в списке
  - Скрывать кнопку Ok
  - Но нажатию на кнопку отмена или повторно кнопку поиска в nav bar-е отменить состояние routeListState, отобразить на карте все маршруты, согласно настройкам отображения, скрыть панель поиска маршрутов
- При выборе "Мои Маршруты" сделать поиск по всем маршрутам текущего пользователя и показать и отобразить их, перейдя в состояние routeListState (см. выше)

**Comment by vlad-86** [comment]
_"По нажатию на кнопку отмена или повторно кнопку поиска в nav bar-е отменить состояние routeListState, отобразить на карте все маршруты, согласно настройкам отображения, скрыть панель поиска маршрутов"_ - не выполняется данное условие.

**Comment by Konstantin86** [comment]
Fixed, теперь при закрытии панели "Маршруты" выполняется апдейт карты с учетом выбранной роли
