### ISSUE TITLE
Сломан механизм поиска  у залогиненого пользователя

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#2]
1.  залогиниться в приложении
2. попробовать проложить маршрут или осуществить поиск через контекстное меню
   </br> **Результат:** в контекстном меню всегда присутствуют кнопки только с назначением "отсюда"
3. вызвать боковую панель для Поиска/Добавления маршрута
4. в полях Окуда/Куда начать вводить улицу
   </br> **Результат:** выпадающий список не отображается

**Ожидаемый результат:** у залогиненного пользователя должен быть аналогичный функционал Поиска/Добавления маршрутов разными способами: контекстное меню/панель меню.

**Comment by Konstantin86** [comment]
Fixed
