### ISSUE TITLE
Боковые меню Поиск/Добавить маршрут не закрываются автоматически при переходе в другие меню

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#3]
1.  залогиниться в приложении
2. вызвать боковую панель для Поиска/Добавления маршрута
3.  Перейти в меню профйалй или вылогиниться
   </br> **Результат:** боковая панель все еще продолжает отображаться.

**Ожидаемый результат:** боковая панель должна скрываться если пользователь кликнул на какой-либо из контроло
![overlapping](https://cloud.githubusercontent.com/assets/5782285/7337462/59e62fd0-ec33-11e4-8e88-8c2b44f150d7.jpg)
в приложения.

**Comment by Konstantin86** [comment]
Fixed
