### ISSUE TITLE
[Bug] В результатах поиска не показывать маршруты самого же пользователя, созданные от противоположной роли

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#33]
. Пользователь в поиске не должен видеть свои маршруты

**Comment by Konstantin86** [comment]
Я пока сделаю отдельной опцией в фильтре поиска, т.к. тяжело поиск будет тестить если в основном все манипуляции со своими маршрутами тестим :)

**Comment by Konstantin86** [comment]
Fixed
