### ISSUE TITLE
В поле для ввода номера телефона можно вводить любые симоволы

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#4]
1.  залогиниться в приложении
2. попробовать проложить маршрут через боковую панель
3.  в поле Контакты ввести произвольные символы "вапывап"
   </br> **Результат:**  вместо телефона есть возможность ввести любые симолы

**Ожидаемый результат:**  в поле Контакты должны вводить только лишь цифры характеризующие номер телефона.
![contact_field](https://cloud.githubusercontent.com/assets/5782285/7337487/34a6e9a2-ec34-11e4-8049-c19b2967c402.jpg)

**Comment by Konstantin86** [comment]
Кандидат на Feature - убрать имя и контакт в настройки профайла пользователя

**Comment by Konstantin86** [comment]
Создал фичу в кот. войдет фикс:
https://github.com/Konstantin86/Git-Hitcher/issues/9
