### ISSUE TITLE
[Bug]  Отсутствует маркер(начальная/конечная)  маршрута

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#48]
1. кликнуть правой кнопкой на карте и выбрать "искать от" или "проложить маршрут"
   <br/>
   Результат: нет маркера на карте показывающего выбранную точку на карте
   <br/> 
   Ожидаемый результат: маркеры присутствуют на карте, показывая крайние точки маршрута

**Comment by Konstantin86** [comment]
fixed
