### ISSUE TITLE
[Bug] Password recovery функционал не отправляет письма

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#55]
1. Зарегистрировать профайл
2. на страничке http://hitcher.com.ua/#/login кликнуть по кнопке Password recovery
3. ввести емэйл только что зарегистрированного пользователя
4. проверить почту
   <br/> 
   Результат: письмо не пришло, хотя было сообщение о том что было отправлено

<br/> 
Ожидаемый: приходит письмо, если емел такой зареган с ссылкой на восстановление пароля.

**Comment by Konstantin86** [comment]
Не могу воспроизвести. Пароль приходит на ура.
