### ISSUE TITLE
Поля телефон/пользователь отображаются как "null"  в бабле

### ISSUE THREAD

**Issue by vlad-86** [Konstantin86/Git-Hitcher#6]
1.  зайти в приложении
2.  проложить маршрут  и не вводить ничего в поля телефон/пользователь
3. вызвать бабл для вноь созданного маршрута
   </br> **Результат:**  поля телефон/пользователь указаны как 'null'

**Ожидаемый результат:**  поля телефон/пользователь должны отображаться пустыми(или скрывать вобще) если он не содержат данных. Для зарегистрированных  пользователей эти данные можно брать с его профайла и подгружать автоматически и не просить его еще раз вводить
![null_entry](https://cloud.githubusercontent.com/assets/5782285/7337554/f637224c-ec36-11e4-9306-001a556d1610.jpg)

**Comment by Konstantin86** [comment]
Создал фичу в кот. войдет фикс:
https://github.com/Konstantin86/Git-Hitcher/issues/9
